-- FlakeHunter initial schema.
-- A project owns runs (one per CI build) and test cases (one per unique test).
-- Each run records one result row per test execution.

CREATE TABLE projects (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(64)  NOT NULL UNIQUE,
    -- SHA-256 of the API key. The plaintext key is shown once at creation and never stored.
    api_key_hash  VARCHAR(64)  NOT NULL UNIQUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE test_runs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT       NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    commit_sha   VARCHAR(40)  NOT NULL,
    branch       VARCHAR(255) NOT NULL,
    build_id     VARCHAR(255),
    total        INT          NOT NULL,
    passed       INT          NOT NULL,
    failed       INT          NOT NULL,
    skipped      INT          NOT NULL,
    duration_ms  BIGINT       NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- "Latest N runs of a project" is the hottest read path (flakiness window).
CREATE INDEX idx_test_runs_project_id_desc ON test_runs (project_id, id DESC);

-- Idempotency: a CI retry that re-uploads the same build must not create a second run.
CREATE UNIQUE INDEX uq_test_runs_project_build ON test_runs (project_id, build_id)
    WHERE build_id IS NOT NULL;

CREATE TABLE test_cases (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id         BIGINT        NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    -- Stable identity of a test across runs: "<suite>::<name>"
    test_key           VARCHAR(1024) NOT NULL,
    suite              VARCHAR(512)  NOT NULL,
    name               VARCHAR(512)  NOT NULL,
    file               VARCHAR(1024),
    quarantined        BOOLEAN       NOT NULL DEFAULT FALSE,
    quarantine_reason  VARCHAR(500),
    quarantined_at     TIMESTAMPTZ,
    CONSTRAINT uq_test_cases_project_key UNIQUE (project_id, test_key)
);

CREATE INDEX idx_test_cases_quarantined ON test_cases (project_id) WHERE quarantined;

CREATE TABLE test_results (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id           BIGINT      NOT NULL REFERENCES test_runs (id) ON DELETE CASCADE,
    test_case_id     BIGINT      NOT NULL REFERENCES test_cases (id) ON DELETE CASCADE,
    status           VARCHAR(16) NOT NULL CHECK (status IN ('PASSED', 'FAILED', 'SKIPPED')),
    duration_ms      BIGINT      NOT NULL,
    failure_message  TEXT
);

CREATE INDEX idx_test_results_run ON test_results (run_id);
CREATE INDEX idx_test_results_case_run ON test_results (test_case_id, run_id DESC);

-- Transactional outbox: events are written in the same transaction as the run,
-- then relayed to Kafka by a background publisher. Avoids the "dual write" problem.
CREATE TABLE outbox_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        UUID         NOT NULL UNIQUE,
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(64)  NOT NULL,
    payload         TEXT         NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at    TIMESTAMPTZ,
    attempts        INT          NOT NULL DEFAULT 0,
    last_error      VARCHAR(1000)
);

CREATE INDEX idx_outbox_unpublished ON outbox_events (id) WHERE published_at IS NULL;
